MANAGER_HELP_TEXT = (
    "[管理者 Bot · 帳號 A]\n"
    "可用指令：\n\n"
    "專案\n"
    "/projects — 列出專案\n"
    "/switch <id> — 切換目前專案（可先 /projects 查 id）\n"
    "/newproject <名稱> — 建立專案\n"
    "/status — 目前專案狀態\n\n"
    "全公司（CEO）\n"
    "/global — 檢視全域設定\n"
    "/updateglobal <欄位> <值> — model、notification（all|failures_only|off）、"
    "dispatch_min_score（0–100）、temperature\n"
    "/addskill <id> — 加入公司 registry skill\n"
    "/removeskill <id> — 移除公司 skill\n"
    "/mode ceo|pm — 切換對話模式\n\n"
    "專案管理（PM）\n"
    "/setupworkers five|three — 建立 workers 範本\n"
    "/addworker backend — 從 worker_default 加入 backend Worker\n"
    "/addprojectskill <id> — 加入專案 skill\n"
    "/repair [interrupt] — PM 維修流程\n"
    "/git <子命令…> — 專案 git（例：/git status）\n\n"
    "其他\n"
    "/start — 連線說明\n"
    "/help — 本說明\n\n"
    "其餘文字訊息依 /mode 由 CEO 或 PM（Gemini）回覆；高風險操作可能出現核准按鈕。"
)

EXECUTOR_HELP_TEXT = (
    "[執行者 Bot · 帳號 B]\n"
    "可用指令：\n\n"
    "/start — 連線說明\n"
    "/help — 本說明\n\n"
    "本 Bot 用於任務進度通知（排程接上 task_scheduler Worker 後推送）。"
    "一般操作請使用管理者 Bot（帳號 A）。"
)
